{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "0350a36c-7f0e-4631-92b8-b917ee98d7cf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3768665-32fd-4e40-b9d5-f72eace5811a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "09f7b8cd-b05c-4052-a922-b1cca50b0fac",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "salesIcrease = 0  #  percentage of increment in sales\n",
    "monthlySales=getSales(\"Enter the monthly sales: \")\n",
    "salesincrease=getIncrease(\"Enter sales increment \")\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    # for user input\n",
    "    monthlySales = float(input(prompt))\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = float(input(prompt))\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "    \n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe425736-346f-4005-94e1-e9ef7252d6f9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "f2c996f6-5a89-4a7c-9869-b5d323c69599",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "26aad368-3782-4c46-99e0-0ad625058f16",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ed84167-572c-4eb0-9012-abfec54c05a7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d3b95c03-f9e3-4a41-bea5-b574f151ecdc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "4fda9416-9115-4760-8333-f9ddb1a8e312",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "3851e4a8-4e93-4e20-9915-58c2cabac85d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dba360d6-be8e-44ed-b466-76795040f4f1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "6e6005a6-3f8d-4f81-9a0d-64eaab25f12f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the monthly sales:  120500\n",
      "Enter sales increment  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "salesIcrease = 0  #  percentage of increment in sales\n",
    "monthlySales=getSales(\"Enter the monthly sales: \")\n",
    "salesincrease=getIncrease(\"Enter sales increment \")\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    # for user input\n",
    "    monthlySales = float(input(prompt))\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = float(input(prompt))\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "    \n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "c083d869-e255-4335-812a-448aa26f324a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The store bonus amount is $ 0\n",
      "The employee bonus amount is $ 0\n"
     ]
    }
   ],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "232e777b-af49-4942-ac32-24b4fdc7fdff",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26adc266-5089-4983-a9e1-4c2d3596484e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Module 4 Lab-4\n",
    "# Gracielle\n",
    "# 10/09/2024\n",
    "# Program to calculate and print store bonus amount and employee bonus amount using functions\n",
    "\n",
    "# declare local variables\n",
    "monthlySales = 0  # monthly sales amount\n",
    "storeAmount = 0  #  store bonus amount\n",
    "empAmount = 0  #  percent of sales increase\n",
    "printBonus(storeAmount, empAmount)\n",
    "\n",
    "# To get the monthly sales information\n",
    "def getSales(prompt):\n",
    "    monthlySales = input(\"Enter the monthly sales $\")\n",
    "    monthlySales = float(monthlySales)\n",
    "\n",
    "    return monthlySales\n",
    "\n",
    "# To calculate the store bonus based on monthly sales\n",
    "def calcStoreBonus(monthlySales):\n",
    "    if monthlySales >= 110000:\n",
    "        storeAmount = 6000\n",
    "    elif monthlySales >= 100000:\n",
    "        storeAmount = 5000\n",
    "    elif monthlySales >= 90000:\n",
    "        storeAmount = 4000\n",
    "    elif monthlysales >= 80000:\n",
    "        storeAmount = 3000\n",
    "    else:\n",
    "        storeAmount = 0\n",
    "\n",
    "    return storeAmount\n",
    "\n",
    "# To calculate the perecentage of increment in sales\n",
    "def getIncrease(prompt):\n",
    "    salesIncrease = input (\"Enter percent of sales increase. For example 4% should be entered as 4: \")\n",
    "    salesIncrease = float(salesIncrease)\n",
    "    salesIncrease = salesIncrease / 100\n",
    "    return salesIncrease\n",
    "\n",
    "# To calculate employee bonus\n",
    "def calcEmpBonus(salesIncrease):\n",
    "    if salesIncrease >= .05:\n",
    "        empAmount = 75\n",
    "    elif salesIncrease >= .04:\n",
    "        empAmount = 50\n",
    "    elif salesIncrease >= .03:\n",
    "        empAmount = 40\n",
    "    else:\n",
    "        empAmount = 0\n",
    "    return empAmount\n",
    "\n",
    "# To print both the bonus information\n",
    "def printBonus( storeAmount, empAmount):\n",
    "    print(\"The store bonus amount is $\", storeAmount)\n",
    "    print(\"The employee bonus amount is $\", empAmount)\n",
    "    if (storeAmount == 6000 ) and (empAmount == 75):\n",
    "        print('Congrats! You have reached the highest bonus amounts possible! ')\n",
    "        \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2eb50d1d-1e4a-4f8e-a3ef-46f423383d96",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
